mapping = {
"APP-HS": 	    "APP-HS - Historical Analysis",
"APP-LA": 	    "APP-LA - Literary Arts",
"APP-PH": 	    "APP-PH- Philosoph/Moral Reason",
"APP-PL": 	    "APP-PL - Physical&Life Science",
"APP-PX": 	    "APP-PX - Phys&Life Sci w/ lab",
"APP-SS": 	    "APP-SS - Social&Behavorial Sci",
"APP-VP": 	    "APP-VP- Visual/Performing Arts",
"CAMPUS-EXP": 	"Campus Life Experience",
"COIL":  	    "Collab Online Intern Learning",
"COMMBEYOND": 	"Communication Beyond Carolina",
"CON-BN": 	    "CON-BN - Beyond North Atlantic",
"CON-CI": 	    "CON-CI - Comm Intensive",
"CON-E1": 	    "CON-E1 - Study Abroad",
"CON-E2": 	    "CON-E2 - Academic Internship",
"CON-E3": 	    "CON-E3 - Service Learning",
"CON-E4": 	    "CON-E4 - Field Work",
"CON-E5": 	    "CON-E5 - Performing Arts",
"CON-E6": 	    "CON-E6 - Mentored Research",
"CON-E7": 	    "CON-E7 - Undergrad Learn Assis",
"CON-E8": 	    "CON-E8 - Conn Exper Educ COIL",
"CON-EE": 	    "General - EE",
"CON-GL": 	    "CON-GL- Global Issues",
"CON-NA": 	    "CON-NA - North Atlantic World",
"CON-QI": 	    "CON-QI- Quantitative Intensive",
"CON-US": 	    "CON-US - U.S. Diversity",
"CON-WB": 	    "CON-WB - The World Before 1750",
"FC-AESTH": 	"Aesthetic & Interpretive Analy",
"FC-CREATE": 	"Creative Expression, Practice",
"FC-GLOBAL": 	"Global Understanding & Engmt",
"FC-KNOWING": 	"Ways of Knowing",
"FC-LAB": 	    "Empirical Investigation Lab",
"FC-NATSCI":  	"Nat Sci Investigation",
"FC-PAST": 	    "Engagement with the Human Past",
"FC-POWER": 	"Power, Difference, Inequality",
"FC-QUANT": 	"Quantitative Reasoning",
"FC-VALUES": 	"Ethical and Civic Values",
"FND-CR": 	    "FND-CR- English Comp&Rhetoric",
"FND-FL": 	    "FND-FL- Foreign Language",
"FND-LF": 	    "FND-LF- Lifetime Fitness",
"FND-QR": 	    "FND-QR- Quantitative Reasoning",
"FY-LAUNCH": 	"First-Year Launch - Section",
"FY-SEMINAR": 	"First Year Seminar",
"FY-THRIVE": 	"First Year Thriving",
"FY-TRIPLE": 	"Ideas, Information and Inquiry",
"FY-WRITING": 	"Writing at the Research Univ",
"GLBL-LANG": 	"Global Language",
"HI-ABROAD": 	"High-Impact: Study Abroad",
"HI-COIL": 	    "High-Impact: COIL",
"HI-GENERAL": 	"High-Impact: General",
"HI-INTERN": 	"High-Impact: Internship",
"HI-LEARNTA": 	"High-Impact: UG Learn Ast",
"HI-PERFORM": 	"High-Impact: Performance",
"HI-RES": 	    "High-Impact: Research",
"HI-SERVICE": 	"High-Impact: Service Learning",
"HNRS": 	    "HNRS - Honors",
"JRSROC": 	    "Junior /Senior Oral Comm",
"LIFE-FIT": 	"Lifetime Fitness",
"RESEARCH": 	"Research and Discovery"
}

def translate(attribute):
    if attribute in mapping.keys():
        return mapping[attribute]
    else:
        return attribute